"""empty message

Revision ID: c7fde18d8408
Revises: 5395a623693a
Create Date: 2019-06-30 18:37:55.019321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fde18d8408'
down_revision = '5395a623693a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawdatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gear', sa.Integer(), nullable=False),
    sa.Column('handbreak', sa.Boolean(), nullable=False),
    sa.Column('maxrpm', sa.Float(), nullable=False),
    sa.Column('rpm', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('pos_z', sa.Float(), nullable=False),
    sa.Column('aa_x', sa.Float(), nullable=False),
    sa.Column('aa_y', sa.Float(), nullable=False),
    sa.Column('aa_z', sa.Float(), nullable=False),
    sa.Column('av_x', sa.Float(), nullable=False),
    sa.Column('av_y', sa.Float(), nullable=False),
    sa.Column('av_z', sa.Float(), nullable=False),
    sa.Column('la_x', sa.Float(), nullable=False),
    sa.Column('la_y', sa.Float(), nullable=False),
    sa.Column('la_z', sa.Float(), nullable=False),
    sa.Column('lv_x', sa.Float(), nullable=False),
    sa.Column('lv_y', sa.Float(), nullable=False),
    sa.Column('lv_z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('users')
    op.drop_table('rawdatas')
    # ### end Alembic commands ###
